import { DevtoolsProvider } from "@providers/devtools";
import { useNotificationProvider } from "@refinedev/antd";
import { Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProvider } from "@providers/auth-provider";
import { dataProvider } from "@providers/data-provider";
import "@refinedev/antd/dist/reset.css";

import { GrBlog, GrServices } from "react-icons/gr";
import { TbCategoryPlus } from "react-icons/tb";
import { FiTag, FiUsers } from "react-icons/fi";
import { FcEditImage } from "react-icons/fc";
import { SlEvent } from "react-icons/sl";
import { AiOutlineFundProjectionScreen } from "react-icons/ai";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <AntdRegistry>
              <ColorModeContextProvider defaultMode={defaultMode}>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    dataProvider={dataProvider}
                    notificationProvider={useNotificationProvider}
                    authProvider={authProvider}
                    resources={[
                      {
                        name: "posts",
                        list: "/dashboard/blog-posts",
                        create: "/dashboard/blog-posts/create",
                        edit: "/dashboard/blog-posts/edit/:id",
                        show: "/dashboard/blog-posts/show/:id",
                        meta: {
                          canDelete: true,
                        },
                        icon: <GrBlog />
                      },
                      {
                        name: "categories",
                        list: "/dashboard/categories",
                        create: "/dashboard/categories/create",
                        edit: "/dashboard/categories/edit/:id",
                        show: "/dashboard/categories/show/:id",
                        meta: {
                          canDelete: true,
                        },
                        icon: <TbCategoryPlus />
                      },
                      {
                        name: "tags",
                        list: "/dashboard/tags",
                        create: "/dashboard/tags/create",
                        edit: "/dashboard/tags/edit/:id",
                        show: "/dashboard/tags/show/:id",
                        meta: {
                          canDelete: true,
                        },
                        icon: <FiTag />
                      },
                      {
                        name: "banners",
                        list: "/dashboard/banners",
                        create: "/dashboard/banners/create",
                        edit: "/dashboard/banners/edit/:id",
                        show: "/dashboard/banners/show/:id",
                        meta: {
                          canDelete: true,
                        },
                        icon: <FcEditImage />
                      },
                      {
                        name: "events",
                        list: "/dashboard/events",
                        create: "/dashboard/events/create",
                        edit: "/dashboard/events/edit/:id",
                        show: "/dashboard/events/show/:id",
                        meta: {
                          canDelete: true,
                        },
                        icon: <SlEvent />
                      },
                      {
                        name: "services",
                        list: "/dashboard/services",
                        create: "/dashboard/services/create",
                        edit: "/dashboard/services/edit/:id",
                        show: "/dashboard/services/show/:id",
                        meta: {
                          canDelete: true,
                        },
                        icon: <GrServices />
                      },
                      {
                        name: "projects",
                        list: "/dashboard/projects",
                        create: "/dashboard/projects/create",
                        edit: "/dashboard/projects/edit/:id",
                        show: "/dashboard/projects/show/:id",
                        meta: {
                          canDelete: true,
                        },
                        icon:<AiOutlineFundProjectionScreen />
                      },
                      {
                        name: "users",
                        list: "/dashboard/users",
                        create: "/dashboard/users/create",
                        edit: "/dashboard/users/edit/:id",
                        show: "/dashboard/users/show/:id",
                        meta: {
                          canDelete: true,
                        },
                        icon: <FiUsers />
                      },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "njMZZm-fu7OWZ-sdebsw",
                      breadcrumb: true,
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </ColorModeContextProvider>
            </AntdRegistry>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
